#!/bin/bash
set -e
sudo mkdir /etc/pipewire
sudo cp -i /usr/share/pipewire/pipewire.conf /etc/pipewire/
sudo cp -i /usr/share/pipewire/pipewire-pulse.conf /etc/pipewire/
sudo ufw enable
sudo rc-update add dbus default
sudo rc-update add elogind boot
sudo rc-update add ufw default
echo "#!/bin/bash
fstrim /" | sudo tee -a /etc/cron.weekly/fstrim
echo "set number" | sudo tee /etc/vim/vimrc
sudo chmod 777 /etc/cron.weekly/fstrim
#sudo mv Fonts/* /usr/share/fonts/
sudo fc-cache -rv
fc-cache -rv
mkdir -p .cache/mpd
