#!/bin/bash
set -eu
sudo mkdir -pv /etc/pipewire/pipewire.conf.d
sudo ln -sv /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
sudo ufw enable
sudo rc-update add dbus default
sudo rc-update add elogind boot
sudo rc-update add ufw default
echo "#!/bin/bash
fstrim /" | sudo tee -a /etc/cron.weekly/fstrim
echo "set showcmd
set number" | sudo tee /etc/vim/vimrc.local
sudo chmod 777 /etc/cron.weekly/fstrim
sudo mv Fonts/* /usr/share/fonts/
sudo fc-cache -rv
fc-cache -rv
mkdir -p .cache/mpd
