#!/bin/bash

for file in "$@"; do
    echo "Extracting $file..."
    case "$file" in
        *.zip) unzip "$file" ;;
        *.tar.gz|*.tgz) tar -xzf "$file" ;;
        *.tar.bz2|*.tbz2) tar -xjf "$file" ;;
        *.tar.xz|*.txz) tar -xJf "$file" ;;
        *.tar.zst) tar --zstd -xf "$file" ;;
        *.tar) tar -xf "$file" ;;
        *.rar) unrar x "$file" ;;
        *.7z) 7z x "$file" ;;
        *.xz) xz -d "$file" ;;
        *.zst) zstd -d "$file" ;;
        *.gz) gunzip "$file" ;;
        *.bz2) bunzip2 "$file" ;;
        *) echo "Skipping $file - unknown format" ;;
    esac
done
echo "Done."
